version: '3.8'

services:
  postgres:
    image: postgres:14
    restart: always
    env_file:
      - .env #Load database credentials from .env file
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./db/postgres_setup.sql:/docker-entrypoint-initdb.d/postgres_setup.sql
    networks:
      - ecommerce_network
  spark:
    build: ./spark
    volumes:
      - ./data:/data:rw
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - ecommerce_network


networks:
  ecommerce_network:
    driver: bridge