version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}

    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
  
  apache-webserver:
    image: apache/airflow
    depends_on:
      - postgres
      - mysql
    environment:
      - AIRFLOW__CORE__EXECUTER=${AIRFLOW__CORE__EXECUTER}
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=${AIRFLOW__DATABASE__SQL_ALCHEMY_CONN}
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./data:/opt/airflow/data
      - .logs:/opt/airflow/logs
    ports:
      - "8080:8080"
    command: webserver