version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}

    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

