
version: '3.8'

services:
  # ZooKeeper service to manage Kafka's metadata and coordination.
  zookeeper:
    image: bitnami/zookeeper:latest # Official Bitnami ZooKeeper image, lightweight and secure.
    ports:
      - "2121:2121" # Exposes ZooKeeper's client port to the host for Kafka to connect.
    volumes:
      - zookeeper_data:/bitnami # Persists ZooKeeper data to avoid loss on container restart.
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes # Allows Kafka to connect without authentication (simple for local dev).
    networks:
      - app-network # Connects to a custom network for communication with Kafka.
  
  # Kafka service for message queuing and streaming.
  kafka:
    image: bitnami/kafka:latest # Official Bitnami Kafka image, supports ZooKeeper-based setup.
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/bitnami # Persists Kafka data (topics, messages) for durability.
    environment:
    # Disables KRaft mode to use ZooKeeper for metadata management.
      - KAFKA_ENABLE_KRAFT=no
    # Specifies ZooKeeper connection (zookeeper service, port 2181).
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2121
    # Configures Kafka to listen on port 9092 with PLAINTEXT protocol (no security for local dev).
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
    # Advertises the listener to clients (localhost:9092 for host access).
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    # Maps listener to PLAINTEXT protocol (no encryption/auth for simplicity).
      - KAFKA_CFG_LISTENERS_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
    # Enables plaintext listener (required for local setup without SSL).
      - ALLOW_PLAINTEXT_LISTENER=yes
    # Sets broker ID (unique for each broker; 1 for single-node setup).
      - KAFKA_BROKER_ID=1
    # Enables auto-creation of topics when producers send data (convenient for testing).
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
    depends_on:
      - zookeeper # Ensures ZooKeeper starts before Kafka, as Kafka relies on it.
    networks:
      - app-network # Connects to the same network as ZooKeeper and other services.

  # PostgreSQL service for storing heart beat data.
  postgresql:
    image: bitnami/postgresql:latest
    ports:
      - "5434:5434"
    volumes:
      - postgres_data:/bitnami/postgresql # Persists database data across restarts.
    # References variables from .env file for security.
    environment:
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
    networks:
      - app-network 

# Kafka-UI service for monitoring Kafka topics and messages.
  kafka-ui:
    image: provectuslabs/kafka-ui:latest # Web-based UI for Kafka monitoring.
    ports:
      - "8080:8080" # Exposes UI on localhost:8080.
    environment:
    # Names the Kafka cluster in the UI.
      - KAFKA_CLUSTERS_0_NAME=local
    # Connects to Kafka broker (kafka:9092).
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    # Connects to ZooKeeper for metadata (optional for UI).
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    depends_on:
      - kafka # Ensures Kafka is running before UI starts.
    networks:
      - app-network # Connects to Kafka and ZooKeeper.

# Persistent volumes for data durability.
volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  postgres_data:
    driver: local

# Custom network for inter-service communication.
networks:
  app-network:
    driver: bridge # Allows containers to communicate via service names (e.g., kafka, postgresql).


  
    
    


