FROM python:3.13-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY scripts/data_generator.py scripts/data_generator.py
COPY scripts/kafka_producer.py scripts/kafka_producer.py
COPY config.yml config.yml

CMD [ "python", "scripts/kafka_producer.py" ]
