version: '3.8'

services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: events_db
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: mypass
    ports:
      - "5433:5432"
    volumes:
      - ./db/postgres_setup.sql:/docker-entrypoint-initdb.d/postgres_setup.sql
    networks:
      - ecommerce_network
  spark:
    build: ./spark
    volumes:
      - ./data:/data
    depends_on:
      - postgres
    networks:
      - ecommerce_network


networks:
  ecommerce_network:
    driver: bridge